import { OffboardingCase } from './types';

export const INITIAL_OFFBOARDING_CASES: OffboardingCase[] = [
  {
    id: 1,
    name: 'Sara Khan',
    initials: 'SK',
    title: 'Front Desk Manager',
    seat: 'FDM-01',
    department: 'Front Office',
    manager: 'James Cole · Hotel Manager',
    joinDate: '10 Mar 2021',
    serviceLength: '5 yrs 6 mos',
    leaveBalance: 12.5,
    reason: 'resignation',
    noticeGivenDate: '14 Sep 2026',
    lastWorkingDay: '14 Oct 2026',
    dueText: 'In 29 days',
    dueTone: 'neu',
    stage: 1, // Serving notice
    successor: 'Omar Haddad',
    handover: [
      {
        key: 'Direct reports',
        title: '3 people report to FDM-01',
        subtitle: 'They stay on the seat and report to Omar Haddad from 15 Oct',
        done: false,
        tag: 'Team & Structure',
      },
      {
        key: 'Approvals',
        title: '2 leave requests waiting on Sara',
        subtitle: 'Reassign to Omar Haddad now',
        done: false,
        tag: 'Operations',
      },
      {
        key: 'Cover',
        title: 'Sara covers Night Manager (NM-01)',
        subtitle: 'Cover ends on her last working day',
        done: true,
        tag: 'Operations',
      },
      {
        key: 'System Access',
        title: 'Opera Cloud PMS Admin privileges transfer',
        subtitle: 'Handover admin privileges to Omar Haddad',
        done: false,
        tag: 'System Access',
      },
      {
        key: 'Shift Keys',
        title: 'Front desk master shift keys handed over',
        subtitle: 'Physical safe and drawer keys deposited',
        done: true,
        tag: 'Physical Assets',
      },
    ],
    clearance: [
      {
        dept: 'IT',
        title: 'Laptop Dell Latitude 5440 returned & PMS access revoked',
        source: 'Assets & Equipment',
        mandatory: true,
        done: false,
        approver: 'Zaid Al-Harbi',
        notes: 'Opera PMS admin access revocations scheduled for Oct 14.',
        status: 'pending',
      },
      {
        dept: 'Admin',
        title: 'ID card, locker 214 and office master key returned',
        source: 'Assets & Equipment',
        mandatory: true,
        done: false,
        approver: 'Tariq Mansoor',
        notes: 'Locker key & name badge return pending.',
        status: 'pending',
      },
      {
        dept: 'Finance',
        title: 'No open salary advances or dues settled',
        source: 'Clearance checklist',
        mandatory: true,
        done: true,
        approver: 'Amina El-Sayed',
        notes: 'Corporate petty cash AED 1,200 verified and settled.',
        status: 'approved',
      },
      {
        dept: 'Line manager',
        title: 'Handover notes received & direct reports reassigned',
        source: 'Clearance checklist',
        mandatory: false,
        done: true,
        approver: 'James Cole',
        notes: 'Handover to Omar in progress. Key briefings completed.',
        status: 'approved',
      },
    ],
    exitInterviewStatus: 'sent',
    settlement: {
      status: 'pending',
      leaveDays: 12.5,
      encashmentAmount: '4,200',
      recoveriesAmount: '350',
      netPayable: '3,850',
      currency: 'AED',
      lettersGenerated: false,
    },
  },
  {
    id: 2,
    name: 'Rahul Mehta',
    initials: 'RM',
    title: 'Sous Chef',
    seat: 'SC-02',
    department: 'Kitchen',
    manager: 'Chef Philippe · Executive Chef',
    joinDate: '1 Jun 2024',
    serviceLength: '2 yrs 3 mos',
    leaveBalance: 8.0,
    reason: 'resignation',
    noticeGivenDate: '2 Sep 2026',
    lastWorkingDay: '2 Oct 2026',
    dueText: 'In 17 days',
    dueTone: 'neu',
    stage: 0, // Notice initiated
    successor: null, // Triggers "No successor" badge
    handover: [
      {
        key: 'Recipe Vault',
        title: 'Main kitchen secret recipes handover',
        subtitle: 'Handed over to Chef Philippe',
        done: false,
        tag: 'Operations',
      },
      {
        key: 'Knife Kit',
        title: 'Knife set and chef HACCP pass deposited',
        subtitle: 'Returned to store',
        done: false,
        tag: 'Physical Assets',
      },
    ],
    clearance: [
      {
        dept: 'IT',
        title: 'Kitchen POS manager credentials reset',
        source: 'Clearance checklist',
        mandatory: true,
        done: false,
        approver: 'Zaid Al-Harbi',
        notes: 'POS access revocation.',
        status: 'pending',
      },
      {
        dept: 'Finance',
        title: 'Kitchen petty cash audit',
        source: 'Clearance checklist',
        mandatory: true,
        done: false,
        approver: 'Amina El-Sayed',
        notes: 'Audit in progress.',
        status: 'pending',
      },
      {
        dept: 'Line manager',
        title: 'Handover notes received',
        source: 'Clearance checklist',
        mandatory: false,
        done: false,
        approver: 'Chef Philippe',
        notes: 'Waiting for recipe binder.',
        status: 'pending',
      },
      {
        dept: 'Admin',
        title: 'Locker & uniform return',
        source: 'Assets & Equipment',
        mandatory: true,
        done: false,
        approver: 'Tariq Mansoor',
        notes: 'Locker inspection pending.',
        status: 'pending',
      },
    ],
    exitInterviewStatus: 'not_sent',
    settlement: {
      status: 'pending',
      leaveDays: 8.0,
      encashmentAmount: '2,800',
      recoveriesAmount: '0',
      netPayable: '2,800',
      currency: 'AED',
      lettersGenerated: false,
    },
  },
  {
    id: 3,
    name: 'Aisha Noor',
    initials: 'AN',
    title: 'Guest Relations Executive',
    seat: 'GR-04',
    department: 'Front Office',
    manager: 'Sara Khan · Front Desk Manager',
    joinDate: '15 May 2025',
    serviceLength: '1 yr 4 mos',
    leaveBalance: 5.0,
    reason: 'termination',
    noticeGivenDate: '12 Sep 2026',
    lastWorkingDay: '12 Sep 2026',
    dueText: 'Left 3 days ago',
    dueTone: 'neu',
    stage: 2, // Exited · clearing
    successor: null,
    handover: [],
    clearance: [
      {
        dept: 'IT',
        title: 'System access terminated',
        source: 'Assets & Equipment',
        mandatory: true,
        done: true,
        approver: 'Zaid Al-Harbi',
        notes: 'Access cut off on 12 Sep.',
        status: 'approved',
      },
      {
        dept: 'Admin',
        title: 'Badge and keycard return',
        source: 'Assets & Equipment',
        mandatory: true,
        done: true,
        approver: 'Tariq Mansoor',
        notes: 'Returned to security.',
        status: 'approved',
      },
      {
        dept: 'Finance',
        title: 'Final deductions calculated',
        source: 'Clearance checklist',
        mandatory: true,
        done: true,
        approver: 'Amina El-Sayed',
        notes: 'Zero dues.',
        status: 'approved',
      },
      {
        dept: 'Line manager',
        title: 'Operational sign-off',
        source: 'Clearance checklist',
        mandatory: false,
        done: true,
        approver: 'Sara Khan',
        notes: 'Signed.',
        status: 'approved',
      },
    ],
    exitInterviewStatus: 'skipped',
    settlement: {
      status: 'paid',
      leaveDays: 5.0,
      encashmentAmount: '1,500',
      recoveriesAmount: '0',
      netPayable: '1,500',
      currency: 'AED',
      lettersGenerated: true,
    },
  },
  {
    id: 4,
    name: 'Leena Joseph',
    initials: 'LJ',
    title: 'Housekeeping Supervisor',
    seat: 'HKS-03',
    department: 'Housekeeping',
    manager: 'Maria Santos · Executive Housekeeper',
    joinDate: '1 Jul 2019',
    serviceLength: '7 yrs 2 mos',
    leaveBalance: 15.0,
    reason: 'retirement',
    noticeGivenDate: '15 Aug 2026',
    lastWorkingDay: '15 Sep 2026',
    dueText: 'Today',
    dueTone: 'bad',
    stage: 1, // Serving notice
    successor: 'Meera Das',
    handover: [
      {
        key: 'Floor keys',
        title: 'All master floor keys deposited',
        subtitle: 'Handed to Maria Santos',
        done: true,
        tag: 'Physical Assets',
      },
    ],
    clearance: [
      {
        dept: 'IT',
        title: 'Radio comms device returned',
        source: 'Assets & Equipment',
        mandatory: true,
        done: true,
        approver: 'Zaid Al-Harbi',
        notes: 'Device checked.',
        status: 'approved',
      },
      {
        dept: 'Finance',
        title: 'Gratuity calculation audit',
        source: 'Clearance checklist',
        mandatory: true,
        done: true,
        approver: 'Amina El-Sayed',
        notes: 'Gratuity verified.',
        status: 'approved',
      },
      {
        dept: 'Admin',
        title: 'Staff accommodation room clearance',
        source: 'Assets & Equipment',
        mandatory: true,
        done: true,
        approver: 'Tariq Mansoor',
        notes: 'Room inspection done.',
        status: 'approved',
      },
      {
        dept: 'Line manager',
        title: 'Final handover sign-off',
        source: 'Clearance checklist',
        mandatory: false,
        done: true,
        approver: 'Maria Santos',
        notes: 'Handover complete.',
        status: 'approved',
      },
    ],
    exitInterviewStatus: 'completed',
    settlement: {
      status: 'in_progress',
      leaveDays: 15.0,
      encashmentAmount: '5,500',
      recoveriesAmount: '0',
      netPayable: '5,500',
      currency: 'AED',
      lettersGenerated: true,
    },
  },
  {
    id: 5,
    name: 'Mark Dsouza',
    initials: 'MD',
    title: 'Security Officer',
    seat: 'SO-07',
    department: 'Security',
    manager: 'Capt. Tariq Al-Hashimi · Security Head',
    joinDate: '1 Aug 2022',
    serviceLength: '4 yrs 1 mo',
    leaveBalance: 0,
    reason: 'retirement',
    noticeGivenDate: '31 Jul 2026',
    lastWorkingDay: '31 Aug 2026',
    dueText: 'Left 15 days ago',
    dueTone: 'neu',
    stage: 3, // Closed
    successor: 'Ravi Kumar',
    handover: [],
    clearance: [
      {
        dept: 'IT',
        title: 'Security cameras credentials revoked',
        source: 'Assets & Equipment',
        mandatory: true,
        done: true,
        approver: 'Zaid Al-Harbi',
        notes: 'Revoked.',
        status: 'approved',
      },
      {
        dept: 'Admin',
        title: 'Uniform & security badge returned',
        source: 'Assets & Equipment',
        mandatory: true,
        done: true,
        approver: 'Tariq Mansoor',
        notes: 'Returned.',
        status: 'approved',
      },
      {
        dept: 'Finance',
        title: 'Settlement disbursed',
        source: 'Clearance checklist',
        mandatory: true,
        done: true,
        approver: 'Amina El-Sayed',
        notes: 'Bank transfer done.',
        status: 'approved',
      },
      {
        dept: 'Line manager',
        title: 'Exit sign-off',
        source: 'Clearance checklist',
        mandatory: false,
        done: true,
        approver: 'Capt. Tariq',
        notes: 'Signed.',
        status: 'approved',
      },
    ],
    exitInterviewStatus: 'completed',
    settlement: {
      status: 'paid',
      leaveDays: 0,
      encashmentAmount: '0',
      recoveriesAmount: '0',
      netPayable: '0',
      currency: 'AED',
      lettersGenerated: true,
    },
  },
];
