import { ApprovalWorkflow } from './types';

export const INITIAL_APPROVAL_WORKFLOWS: ApprovalWorkflow[] = [
  // --- EXPENSE (8 Workflows) ---
  {
    id: 'wf_exp_01',
    name: 'Standard Expense Policy',
    description: 'Auto-configured global fallback policy for all employee expense claims.',
    module: 'expense',
    policyType: 'default',
    status: 'active',
    version: '1.4',
    priorityRank: 99,
    conditions: [],
    steps: [
      {
        id: 'step_exp_01_1',
        order: 1,
        label: 'Direct Manager Approval',
        routingMethod: 'direct_manager',
        hierarchyDepth: 1,
        slaHours: 48,
        preventSelfApproval: true,
        required: true,
      },
      {
        id: 'step_exp_01_2',
        order: 2,
        label: 'Finance Lead Sign-off',
        routingMethod: 'role_queue',
        assigneeRole: 'Finance Controller',
        slaHours: 48,
        required: true,
      },
    ],
    fallbackPolicy: {
      onVacantApprover: 'skip_to_next',
      allowDelegation: true,
    },
    inFlightCount: 6,
    lastModifiedBy: 'Vikram Malhotra',
    lastModifiedDate: '12 Sep 2026',
  },
  {
    id: 'wf_exp_02',
    name: 'Executive & Travel Reimbursements > $5,000',
    description: 'High-value flight, lodging, and client entertainment authorization.',
    module: 'expense',
    policyType: 'scoped',
    status: 'active',
    version: '2.1',
    priorityRank: 1,
    conditions: [
      { id: 'c_1', field: 'amount', operator: 'greater_than', value: 5000 },
      { id: 'c_2', field: 'department', operator: 'in', value: ['Executive', 'Sales', 'Corporate'] },
    ],
    steps: [
      {
        id: 'step_exp_02_1',
        order: 1,
        label: 'Direct Reporting Manager',
        routingMethod: 'direct_manager',
        hierarchyDepth: 1,
        slaHours: 24,
        preventSelfApproval: true,
        required: true,
      },
      {
        id: 'step_exp_02_2',
        order: 2,
        label: 'Vice President of Division',
        routingMethod: 'skip_level_manager',
        hierarchyDepth: 2,
        slaHours: 24,
        required: true,
      },
      {
        id: 'step_exp_02_3',
        order: 3,
        label: 'Chief Financial Officer',
        routingMethod: 'specific_person',
        assigneeName: 'Priya Sharma',
        assigneeRole: 'CFO',
        assigneeAvatar: 'PS',
        slaHours: 48,
        required: true,
      },
    ],
    fallbackPolicy: {
      onVacantApprover: 'escalate_to_skip',
      allowDelegation: true,
    },
    inFlightCount: 4,
    lastModifiedBy: 'Chanchal Sharma',
    lastModifiedDate: '15 Sep 2026',
  },
  {
    id: 'wf_exp_03',
    name: 'F&B Culinary & Kitchen Bulk Supplies',
    description: 'Specialized inventory claims for food, beverage, and perishable perishables.',
    module: 'expense',
    policyType: 'scoped',
    status: 'active',
    version: '1.2',
    priorityRank: 2,
    conditions: [
      { id: 'c_3', field: 'department', operator: 'equals', value: 'Food & Beverage' },
      { id: 'c_4', field: 'category', operator: 'equals', value: 'Kitchen Supplies' },
    ],
    steps: [
      {
        id: 'step_exp_03_1',
        order: 1,
        label: 'Executive Head Chef Sign-off',
        routingMethod: 'role_queue',
        assigneeRole: 'Executive Chef',
        slaHours: 24,
        required: true,
      },
      {
        id: 'step_exp_03_2',
        order: 2,
        label: 'F&B Director Review',
        routingMethod: 'department_head',
        slaHours: 24,
        required: true,
      },
      {
        id: 'step_exp_03_3',
        order: 3,
        label: 'Purchasing Controller',
        routingMethod: 'role_queue',
        assigneeRole: 'Procurement Specialist',
        slaHours: 48,
        required: true,
      },
    ],
    inFlightCount: 3,
    lastModifiedBy: 'Rahul Mehta',
    lastModifiedDate: '10 Sep 2026',
  },
  {
    id: 'wf_exp_04',
    name: 'Petty Cash Instant Auto-Pass (<= $50)',
    description: 'Zero-touch automated approval for micro-expenses and local transport taxi slips.',
    module: 'expense',
    policyType: 'scoped',
    status: 'active',
    version: '1.0',
    priorityRank: 3,
    conditions: [
      { id: 'c_5', field: 'amount', operator: 'less_than', value: 50 },
    ],
    steps: [
      {
        id: 'step_exp_04_1',
        order: 1,
        label: 'Instant Auto-Approve & Audit Log',
        routingMethod: 'auto_approve',
        slaHours: 0,
        required: true,
      },
    ],
    inFlightCount: 5,
    lastModifiedBy: 'Vikram Malhotra',
    lastModifiedDate: '01 Sep 2026',
  },
  {
    id: 'wf_exp_05',
    name: 'Sales Client Entertainment & Dining',
    description: 'Client dinners, customer gifts, and partnership business development expenses.',
    module: 'expense',
    policyType: 'scoped',
    status: 'active',
    version: '1.1',
    priorityRank: 4,
    conditions: [
      { id: 'c_6', field: 'department', operator: 'equals', value: 'Sales & Marketing' },
    ],
    steps: [
      {
        id: 'step_exp_05_1',
        order: 1,
        label: 'Director of Sales Approval',
        routingMethod: 'department_head',
        slaHours: 48,
        required: true,
      },
      {
        id: 'step_exp_05_2',
        order: 2,
        label: 'Finance Audit Lead',
        routingMethod: 'role_queue',
        assigneeRole: 'Finance Controller',
        slaHours: 48,
        required: true,
      },
    ],
    inFlightCount: 2,
    lastModifiedBy: 'Priya Sharma',
    lastModifiedDate: '14 Sep 2026',
  },
  {
    id: 'wf_exp_06',
    name: 'Front Office Operations & Desk Sundries',
    description: 'Guest relations supplies, keycards, and reception logistics.',
    module: 'expense',
    policyType: 'scoped',
    status: 'active',
    version: '1.3',
    priorityRank: 5,
    conditions: [
      { id: 'c_7', field: 'department', operator: 'equals', value: 'Front Office' },
    ],
    steps: [
      {
        id: 'step_exp_06_1',
        order: 1,
        label: 'Front Desk Manager Review',
        routingMethod: 'direct_manager',
        slaHours: 24,
        required: true,
      },
      {
        id: 'step_exp_06_2',
        order: 2,
        label: 'Operations Finance',
        routingMethod: 'role_queue',
        assigneeRole: 'Finance Controller',
        slaHours: 48,
        required: true,
      },
    ],
    inFlightCount: 1,
    lastModifiedBy: 'Sara Khan',
    lastModifiedDate: '08 Sep 2026',
  },
  {
    id: 'wf_exp_07',
    name: 'Housekeeping Equipment & Linen Replacements',
    description: 'Cleaning machinery repairs, chemical refills, and guest linen batches.',
    module: 'expense',
    policyType: 'scoped',
    status: 'active',
    version: '1.0',
    priorityRank: 6,
    conditions: [
      { id: 'c_8', field: 'department', operator: 'equals', value: 'Housekeeping' },
    ],
    steps: [
      {
        id: 'step_exp_07_1',
        order: 1,
        label: 'Executive Housekeeper Sign-off',
        routingMethod: 'department_head',
        slaHours: 36,
        required: true,
      },
      {
        id: 'step_exp_07_2',
        order: 2,
        label: 'Property General Manager',
        routingMethod: 'specific_person',
        assigneeName: 'Vikram Malhotra',
        assigneeRole: 'General Manager',
        assigneeAvatar: 'VM',
        slaHours: 48,
        required: true,
      },
    ],
    inFlightCount: 1,
    lastModifiedBy: 'Leena Joseph',
    lastModifiedDate: '04 Sep 2026',
  },
  {
    id: 'wf_exp_08',
    name: 'IT Hardware & Cloud Subscriptions (Draft)',
    description: 'Workstation purchases, server upgrades, and SaaS licensing.',
    module: 'expense',
    policyType: 'scoped',
    status: 'draft',
    version: '0.9',
    priorityRank: 7,
    conditions: [
      { id: 'c_9', field: 'department', operator: 'equals', value: 'Information Technology' },
    ],
    steps: [
      {
        id: 'step_exp_08_1',
        order: 1,
        label: 'IT Infrastructure Lead',
        routingMethod: 'role_queue',
        assigneeRole: 'IT Systems Admin',
        slaHours: 48,
        required: true,
      },
    ],
    inFlightCount: 0,
    lastModifiedBy: 'Chanchal Sharma',
    lastModifiedDate: '17 Sep 2026',
  },

  // --- LEAVE (3 Workflows) ---
  {
    id: 'wf_leave_01',
    name: 'Standard Annual & Sick Leave Policy',
    description: 'Default 1-level manager sign-off for standard paid time off and sick days.',
    module: 'leave',
    policyType: 'default',
    status: 'active',
    version: '1.0',
    priorityRank: 99,
    conditions: [],
    steps: [
      {
        id: 'step_leave_01_1',
        order: 1,
        label: 'Direct Line Manager Approval',
        routingMethod: 'direct_manager',
        hierarchyDepth: 1,
        slaHours: 48,
        preventSelfApproval: true,
        required: true,
      },
    ],
    inFlightCount: 7,
    lastModifiedBy: 'Vikram Malhotra',
    lastModifiedDate: '02 Sep 2026',
  },
  {
    id: 'wf_leave_02',
    name: 'Extended Executive Sabbatical (> 10 Days)',
    description: 'Multi-tier review for extended leaves exceeding 10 consecutive business days.',
    module: 'leave',
    policyType: 'scoped',
    status: 'active',
    version: '1.3',
    priorityRank: 1,
    conditions: [
      { id: 'c_10', field: 'tenure', operator: 'greater_than', value: 10 },
      { id: 'c_11', field: 'grade', operator: 'in', value: ['L7', 'L8', 'L9'] },
    ],
    steps: [
      {
        id: 'step_leave_02_1',
        order: 1,
        label: 'Reporting Line Manager',
        routingMethod: 'direct_manager',
        slaHours: 24,
        required: true,
      },
      {
        id: 'step_leave_02_2',
        order: 2,
        label: 'Property General Manager',
        routingMethod: 'specific_person',
        assigneeName: 'Vikram Malhotra',
        assigneeRole: 'General Manager',
        assigneeAvatar: 'VM',
        slaHours: 48,
        required: true,
      },
    ],
    inFlightCount: 2,
    lastModifiedBy: 'Vikram Malhotra',
    lastModifiedDate: '11 Sep 2026',
  },
  {
    id: 'wf_leave_03',
    name: 'Maternity, Paternity & Adoption Leave',
    description: 'Statutory family leaves with HR benefits and payroll alignment.',
    module: 'leave',
    policyType: 'scoped',
    status: 'active',
    version: '1.1',
    priorityRank: 2,
    conditions: [
      { id: 'c_12', field: 'category', operator: 'equals', value: 'Parental Leave' },
    ],
    steps: [
      {
        id: 'step_leave_03_1',
        order: 1,
        label: 'Direct Reporting Manager',
        routingMethod: 'direct_manager',
        slaHours: 48,
        required: true,
      },
      {
        id: 'step_leave_03_2',
        order: 2,
        label: 'HR People Operations & Benefits',
        routingMethod: 'role_queue',
        assigneeRole: 'HR People Partner',
        slaHours: 24,
        required: true,
      },
    ],
    inFlightCount: 1,
    lastModifiedBy: 'Priya Sharma',
    lastModifiedDate: '06 Sep 2026',
  },

  // --- ATTENDANCE CORRECTION (1 Workflow) ---
  {
    id: 'wf_att_01',
    name: 'Shift & Biometric Attendance Regularization',
    description: 'Line supervisor review for missed punch-ins, clock anomalies, and shift changes.',
    module: 'attendance',
    policyType: 'default',
    status: 'active',
    version: '1.2',
    priorityRank: 99,
    conditions: [],
    steps: [
      {
        id: 'step_att_01_1',
        order: 1,
        label: 'Shift Supervisor Sign-off',
        routingMethod: 'direct_manager',
        slaHours: 24,
        preventSelfApproval: true,
        required: true,
      },
      {
        id: 'step_att_01_2',
        order: 2,
        label: 'HR Timekeeper Audit',
        routingMethod: 'role_queue',
        assigneeRole: 'HR Timekeeper',
        slaHours: 24,
        required: true,
      },
    ],
    inFlightCount: 8,
    lastModifiedBy: 'Chanchal Sharma',
    lastModifiedDate: '13 Sep 2026',
  },

  // --- POSITION APPROVAL (1 Workflow) ---
  {
    id: 'wf_pos_01',
    name: 'New Headcount & Seat Requisition Flow',
    description: '3-tier organizational sign-off to authorize creation or replacement of headcount.',
    module: 'position',
    policyType: 'default',
    status: 'active',
    version: '2.0',
    priorityRank: 99,
    conditions: [],
    steps: [
      {
        id: 'step_pos_01_1',
        order: 1,
        label: 'Hiring Department Head',
        routingMethod: 'department_head',
        slaHours: 48,
        required: true,
      },
      {
        id: 'step_pos_01_2',
        order: 2,
        label: 'Director of Finance',
        routingMethod: 'role_queue',
        assigneeRole: 'Finance Controller',
        slaHours: 48,
        required: true,
      },
      {
        id: 'step_pos_01_3',
        order: 3,
        label: 'Property General Manager',
        routingMethod: 'specific_person',
        assigneeName: 'Vikram Malhotra',
        assigneeRole: 'General Manager',
        assigneeAvatar: 'VM',
        slaHours: 72,
        required: true,
      },
    ],
    inFlightCount: 2,
    lastModifiedBy: 'Vikram Malhotra',
    lastModifiedDate: '09 Sep 2026',
  },

  // --- NOTICE PERIOD & EXIT (1 Workflow) ---
  {
    id: 'wf_not_01',
    name: 'Notice Period Default Flow',
    description: 'Auto-configured approval flow for planned departures and notice periods.',
    module: 'notice_period',
    policyType: 'default',
    status: 'active',
    version: '1.0',
    priorityRank: 99,
    conditions: [],
    steps: [
      {
        id: 'step_not_01_1',
        order: 1,
        label: 'Direct Manager Approval',
        routingMethod: 'direct_manager',
        hierarchyDepth: 1,
        slaHours: 48,
        preventSelfApproval: true,
        required: true,
      },
      {
        id: 'step_not_01_2',
        order: 2,
        label: 'HR People Partner Sign-off',
        routingMethod: 'role_queue',
        assigneeRole: 'HR Director',
        slaHours: 48,
        required: true,
      },
    ],
    inFlightCount: 4,
    lastModifiedBy: 'Chanchal Sharma',
    lastModifiedDate: '16 Sep 2026',
  },
];
